### ISSUE TITLE
Empty object being returned

### ISSUE THREAD

**Issue by RileySpiller** [jackfranklin/gulp-load-plugins#70]
I'm getting `{}` returned by running...

```javascript
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')({lazy: false});
console.log(JSON.stringify(plugins));
```

I set `lazy: false` after reading this issue https://github.com/jackfranklin/gulp-load-plugins/issues/58

And I my package.json is packed full of plugins, many with or without 'gulp-' prefix. 

Any help appreciated.

**Comment by MarkAPhillips** [comment]
```
console.log(JSON.stringify(plugins));
```

I think does not return all the plugins as ran into this issue myself and only one was returned to the console and wondered why they were not all being loaded. Not sure what this should returned but you would expect all plugins to be shown if lazy is false

I would suggest you run a few plugins to see if they work as expected.

My config at the moment is as follows and works like a dream:

```
var path = require('path');
var gulpLoadPlugins = require('gulp-load-plugins');
var gulp = require('gulp');
   
var pluginOpts = {
        config: path.join(__dirname,'package.json'),
        replaceString: /^gulp(-|\.)/,
        scope: ['devDependencies'],
        lazy: false
};

var plugins = gulpLoadPlugins(pluginOpts);
```

**Comment by jackfranklin** [comment]
>  Not sure what this should return but you would expect all plugins to be shown if lazy is false

Yeah, I would. Not sure what's going on there.

@RileySpiller did you get to the bottom of this?

**Comment by AutoSponge** [comment]
:+1:  same issue

**Comment by callumacrae** [comment]
@AutoSponge Do you definitely have `lazy` set to false?

**Comment by AutoSponge** [comment]
Yes. I've tried multiple versions of node, throwing tasks inside nextTick, etc. Nothing seems to work yet.

**Comment by callumacrae** [comment]
If you clone this repo locally, do the tests pass for you?

**Comment by callumacrae** [comment]
Hang on, the error indicates that `plugins.sass` _is_ defined, otherwise it would say "cannot read property of undefined".

What happens if you run `console.log(plugins)`?

**Comment by AutoSponge** [comment]
empty object. If I do `console.log(Object.keys(plugins))` empty array.

**Comment by jackfranklin** [comment]
What does `plugins.sass.toString()` log?

**Comment by AutoSponge** [comment]
TypeError: Cannot read property 'toString' of undefined

**Comment by AutoSponge** [comment]
I can try to build from master.

**Comment by AutoSponge** [comment]
Possible hint: I removed all of the config *except* `lazy: true` and that worked!

Something else in the config object I posted earlier must be messing with plugin names. So, I added a console.log:

```js
    } else {
      console.log(requireName, name);
      object[requireName] = requireFn(name);
    }

```

With the original config, it never reaches this... it's not getting any plugins.

**Comment by callumacrae** [comment]
Hang on, are you using `lazy: true` now? Originally you were using `lazy: false`

**Comment by jackfranklin** [comment]
@AutoSponge are you able to recreate this issue in a repo you could push to GitHub for me to take a look at?

**Comment by AutoSponge** [comment]
@callumacrae I'm using `plugins = require('gulp-load-plugins')({lazy: false});` The issue went away when I removed the other config options and *just* passed the lazy value. I think there's another option silently erroring out.

@jackfranklin I'll try to make a gist or something tonight.

**Comment by jackfranklin** [comment]
@AutoSponge sounds like another config is causing issues. If you could give me something that I can replicate I'll happily debug. Sorry you're having problems and thanks for being responsive!

**Comment by AutoSponge** [comment]
I think it was caused by the relative path`./package.json`. 

Removing the `./` or using the smarter `config: path.join(__dirname, 'package.json'),` should fix this for others.

```js
var gulp = require('gulp');
var path = require('path');
var plugins = require('gulp-load-plugins')({
    config: path.join(__dirname, 'package.json'),
    lazy: false
});
```

**Comment by jackfranklin** [comment]
@AutoSponge ahh OK. That's interesting, would be nice to show a different error rather than just silently failing weird. I'll see if I can get something going.

**Comment by jfairley** [comment]
What @AutoSponge discovered is similar to https://github.com/jackfranklin/gulp-load-plugins/issues/76

**Comment by pushkin-** [comment]
I have a similar problem as above, but adding the `config` parameter doesn't solve it.

    var gulp = require('gulp');
    var path = require('path');
    var plugins = require('gulp-load-plugins')({
        config: path.join(__dirname, 'package.json'),
        lazy: false
    });

Printing this gives me: 

    {
      "util": {
          "colors": {
              "enabled": true,
              "styles": {
                  "reset": {
                      "open": "\u001b[0m",
                      "close": "\u001b[0m",
                      "closeRe": {}
                  },
                  "bold": {
                      "open": "\u001b[1m",
                      "close": "\u001b[22m",
                      "closeRe": {}
                  },
    ...

"util" is the only thing there. Has anyone had this issue?

**Comment by TNT-Likely** [comment]
i have a problem as same as  @AutoSponge 

how do you slove?

**Comment by jackfranklin** [comment]
@pushkin- 

>  It seems to default to removing the gulp prefix even if I'm not using the parameter replaceString (is this a bug?).

Nope, the default behaviour removes `gulp-` and `gulp.` from package names.

Presumably it doesn't work if you remove the `config` param either?

@TNT-Likely we're not sure yet, haven't been able to lock down exactly what's going wrong.

@pushkin- @TNT-Likely if either of you can push a repo that replicates this then I'm happy to dig into it :+1:

**Comment by TNT-Likely** [comment]
i reslove it ,when i use version 0.10.0,it work,it seems the lastest vesion have some problems.
@jackfranklin

**Comment by pushkin-** [comment]
@jackfranklin Correct. It doesn't work without the config parameter.

**Comment by jackfranklin** [comment]
If anyone could run this against v1.1.0 with `DEBUG: true` set, the output from that might shed some light?

**Comment by jackfranklin** [comment]
@RileySpiller did you get anywhere with this?

I think that I'm going to close this shortly given it's not had an update really since August. If anyone is hitting this though please let me know - and a repository that replicates the issue I can clone would be awesome too.

**Comment by SamHH** [comment]
I gave up on the plugin upon encountering this issue months ago. I'd be happy to give it another go and pass you the repo if the issue reoccurs. Hopefully will get that to you later today.

**Comment by SamHH** [comment]
Turns out that I can no longer recreate this issue. That's a good thing, I think.

**Comment by jackfranklin** [comment]
@SamHH that's good news! I still don't know what caused it, which is frustrating, but perhaps it was a random edge case a recent release fixed.
